# Generated by Django 4.2.7 on 2025-07-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='placa',
        ),
        migrations.AddField(
            model_name='bus',
            name='nombre',
            field=models.CharField(default='ida', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paradero',
            name='orientacion',
            field=models.CharField(choices=[('ida', 'Ida'), ('vuelta', 'Vuelta')], default='ida', help_text='Indica si el paradero es para la ruta de ida o de vuelta.', max_length=10),
        ),
    ]
