# Generated by Django 4.2.7 on 2025-07-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_bus_placa_bus_nombre_paradero_orientacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='paradero',
            name='orientacion',
        ),
        migrations.AddField(
            model_name='bus',
            name='placa',
            field=models.CharField(default='ida', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
