# Generated by Django 4.2.7 on 2025-07-13 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_remove_bus_placa_bus_nombre_paradero_orientacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='ultima_actualizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ubicacionbus',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
