# Generated by Django 4.2.7 on 2025-07-14 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_bus_ultima_actualizacion_ubicacionbus_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orientacion', models.CharField(choices=[('ida', 'Ida'), ('vuelta', 'Vuelta')], help_text='Orientación de la ruta (ida o vuelta)', max_length=10)),
                ('tipo_segmento', models.CharField(choices=[('inicio', 'Segmento Inicial'), ('final', 'Segmento Final')], help_text='Indica si es el segmento inicial o final de la ruta', max_length=20)),
                ('coordenadas', models.TextField(help_text='JSON con array de coordenadas [[lat, lng], [lat, lng], ...]')),
                ('activo', models.BooleanField(default=True)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.ruta')),
            ],
            options={
                'ordering': ['ruta', 'orientacion', 'tipo_segmento'],
                'unique_together': {('ruta', 'orientacion', 'tipo_segmento')},
            },
        ),
    ]
